### ISSUE TITLE
Thumbnail generator error with image cropping

### ISSUE THREAD

**Issue by ngwk1** [osrf/traffic_editor#190]
I have received an error for using the script `crop.py`:

```
Traceback (most recent call last):
  File "./scripts/crop.py", line 149, in <module>
    white_img_cropped = crop(green_img, white_img)
  File "./scripts/crop.py", line 32, in crop
    mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
ValueError: need more than 2 values to unpack
```

I fixed it by changing the number of outputs from:
`   _ ,  contours, _ = cv2.findContours( mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE) `
to 
`    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)`

**Comment by aaronchongth** [comment]
thanks for finding that issue, this is probably due to different versions of OpenCV, while the version shipped with ROS prefers the latter version. I'll make the necessary fixes, thanks!

**Comment by aaronchongth** [comment]
@ngwk1 alternative, you could take a look at this new pipeline, it should work as expected. if you find any issues, feel free to reach out
https://github.com/osrf/traffic_editor/pull/191

**Comment by tanyouliang95** [comment]
Yes, we have a replacement for the existing `thumbnail_generator`. Can close this issue for now. Thanks for raising this :+1:
